/*
 * Froody API
 * API for Froody - http://froodyapp.gsantner.net/
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.froodyapp.api.model_;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * General result, returns success or failure of a call
 */
@ApiModel(description = "General result, returns success or failure of a call")

public class ServerOverallStats implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("userCount")
  private Long userCount = null;

  @SerializedName("entryCount")
  private Long entryCount = null;

  public ServerOverallStats userCount(Long userCount) {
    this.userCount = userCount;
    return this;
  }

   /**
   * User.checkDate ** Count of users checking in the last ENTRY_LIFETIME_DAYS days
   * @return userCount
  **/
  @ApiModelProperty(value = "User.checkDate ** Count of users checking in the last ENTRY_LIFETIME_DAYS days")
  public Long getUserCount() {
    return userCount;
  }

  public void setUserCount(Long userCount) {
    this.userCount = userCount;
  }

  public ServerOverallStats entryCount(Long entryCount) {
    this.entryCount = entryCount;
    return this;
  }

   /**
   * Entry.modificationDate ** Count of active entries
   * @return entryCount
  **/
  @ApiModelProperty(value = "Entry.modificationDate ** Count of active entries")
  public Long getEntryCount() {
    return entryCount;
  }

  public void setEntryCount(Long entryCount) {
    this.entryCount = entryCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerOverallStats serverOverallStats = (ServerOverallStats) o;
    return Objects.equals(this.userCount, serverOverallStats.userCount) &&
        Objects.equals(this.entryCount, serverOverallStats.entryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userCount, entryCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerOverallStats {\n");
    
    sb.append("    userCount: ").append(toIndentedString(userCount)).append("\n");
    sb.append("    entryCount: ").append(toIndentedString(entryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

