/*
 * Froody API
 * API for Froody - http://froody-app.at/
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.froodyapp.api.api;

import io.github.froodyapp.api.invoker.ApiCallback;
import io.github.froodyapp.api.invoker.ApiClient;
import io.github.froodyapp.api.invoker.ApiException;
import io.github.froodyapp.api.invoker.ApiResponse;
import io.github.froodyapp.api.invoker.Configuration;
import io.github.froodyapp.api.invoker.Pair;
import io.github.froodyapp.api.invoker.ProgressRequestBody;
import io.github.froodyapp.api.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.github.froodyapp.api.model_.BlockInfo;
import org.joda.time.DateTime;
import io.github.froodyapp.api.model_.FroodyEntry;
import io.github.froodyapp.api.model_.ResponseOk;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BlockApi {
    private ApiClient apiClient;

    public BlockApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BlockApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for blockGetGet
     * @param geohash Entry.geohash ** Geohash which should be matched (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call blockGetGetCall(String geohash, DateTime minModificationDate, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/block/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (geohash != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "geohash", geohash));
        if (minModificationDate != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "minModificationDate", minModificationDate));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call blockGetGetValidateBeforeCall(String geohash, DateTime minModificationDate, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'geohash' is set
        if (geohash == null) {
            throw new ApiException("Missing the required parameter 'geohash' when calling blockGetGet(Async)");
        }
        
        // verify the required parameter 'minModificationDate' is set
        if (minModificationDate == null) {
            throw new ApiException("Missing the required parameter 'minModificationDate' when calling blockGetGet(Async)");
        }
        
        
        com.squareup.okhttp.Call call = blockGetGetCall(geohash, minModificationDate, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * Entry[ ] ** Get entries contained in block
     * @param geohash Entry.geohash ** Geohash which should be matched (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification (required)
     * @return List&lt;FroodyEntry&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<FroodyEntry> blockGetGet(String geohash, DateTime minModificationDate) throws ApiException {
        ApiResponse<List<FroodyEntry>> resp = blockGetGetWithHttpInfo(geohash, minModificationDate);
        return resp.getData();
    }

    /**
     * 
     * Entry[ ] ** Get entries contained in block
     * @param geohash Entry.geohash ** Geohash which should be matched (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification (required)
     * @return ApiResponse&lt;List&lt;FroodyEntry&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<FroodyEntry>> blockGetGetWithHttpInfo(String geohash, DateTime minModificationDate) throws ApiException {
        com.squareup.okhttp.Call call = blockGetGetValidateBeforeCall(geohash, minModificationDate, null, null);
        Type localVarReturnType = new TypeToken<List<FroodyEntry>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Entry[ ] ** Get entries contained in block
     * @param geohash Entry.geohash ** Geohash which should be matched (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call blockGetGetAsync(String geohash, DateTime minModificationDate, final ApiCallback<List<FroodyEntry>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = blockGetGetValidateBeforeCall(geohash, minModificationDate, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<FroodyEntry>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for blockInfoGet
     * @param geohash BlockInfo.geohash ** Geohash (&#x3D;position)  (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification. Make ENTRY_LIFETIME_DAYS days ago to get everything. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call blockInfoGetCall(String geohash, DateTime minModificationDate, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/block/info";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (geohash != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "geohash", geohash));
        if (minModificationDate != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "minModificationDate", minModificationDate));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call blockInfoGetValidateBeforeCall(String geohash, DateTime minModificationDate, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'geohash' is set
        if (geohash == null) {
            throw new ApiException("Missing the required parameter 'geohash' when calling blockInfoGet(Async)");
        }
        
        // verify the required parameter 'minModificationDate' is set
        if (minModificationDate == null) {
            throw new ApiException("Missing the required parameter 'minModificationDate' when calling blockInfoGet(Async)");
        }
        
        
        com.squareup.okhttp.Call call = blockInfoGetCall(geohash, minModificationDate, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * Get informations about of or around block/geohash
     * @param geohash BlockInfo.geohash ** Geohash (&#x3D;position)  (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification. Make ENTRY_LIFETIME_DAYS days ago to get everything. (required)
     * @return List&lt;BlockInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<BlockInfo> blockInfoGet(String geohash, DateTime minModificationDate) throws ApiException {
        ApiResponse<List<BlockInfo>> resp = blockInfoGetWithHttpInfo(geohash, minModificationDate);
        return resp.getData();
    }

    /**
     * 
     * Get informations about of or around block/geohash
     * @param geohash BlockInfo.geohash ** Geohash (&#x3D;position)  (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification. Make ENTRY_LIFETIME_DAYS days ago to get everything. (required)
     * @return ApiResponse&lt;List&lt;BlockInfo&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<BlockInfo>> blockInfoGetWithHttpInfo(String geohash, DateTime minModificationDate) throws ApiException {
        com.squareup.okhttp.Call call = blockInfoGetValidateBeforeCall(geohash, minModificationDate, null, null);
        Type localVarReturnType = new TypeToken<List<BlockInfo>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Get informations about of or around block/geohash
     * @param geohash BlockInfo.geohash ** Geohash (&#x3D;position)  (required)
     * @param minModificationDate BlockInfo.modificationDate ** Timestamp of last known block modification. Make ENTRY_LIFETIME_DAYS days ago to get everything. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call blockInfoGetAsync(String geohash, DateTime minModificationDate, final ApiCallback<List<BlockInfo>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = blockInfoGetValidateBeforeCall(geohash, minModificationDate, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<BlockInfo>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for blockInfoRandomGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call blockInfoRandomGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/block/info/random";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call blockInfoRandomGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = blockInfoRandomGetCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * Get informations about random geohashes
     * @return List&lt;BlockInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<BlockInfo> blockInfoRandomGet() throws ApiException {
        ApiResponse<List<BlockInfo>> resp = blockInfoRandomGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * 
     * Get informations about random geohashes
     * @return ApiResponse&lt;List&lt;BlockInfo&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<BlockInfo>> blockInfoRandomGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = blockInfoRandomGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<List<BlockInfo>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Get informations about random geohashes
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call blockInfoRandomGetAsync(final ApiCallback<List<BlockInfo>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = blockInfoRandomGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<BlockInfo>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
