/*
 * Froody API
 * API for Froody - http://froody-app.at/
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.froodyapp.api.api;

import io.github.froodyapp.api.invoker.ApiException;
import io.github.froodyapp.api.model_.ResponseOk;
import io.github.froodyapp.api.model_.ServerOverallStats;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatsApi
 */
@Ignore
public class StatsApiTest {

    private final StatsApi api = new StatsApi();

    
    /**
     * 
     *
     * Overall statistics
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void statsOverallGetTest() throws ApiException {
        ServerOverallStats response = api.statsOverallGet();

        // TODO: test validations
    }
    
}
