/*
 * Froody API
 * API for Froody - http://froodyapp.gsantner.net/
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.froodyapp.api.api;

import io.github.froodyapp.api.invoker.ApiException;
import io.github.froodyapp.api.model_.FroodyUser;
import io.github.froodyapp.api.model_.ResponseOk;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * 
     *
     * Check if user is enabled (by User.userId)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userIsEnabledGetTest() throws ApiException {
        Long userId = null;
        ResponseOk response = api.userIsEnabledGet(userId);

        // TODO: test validations
    }
    
    /**
     * User Id
     *
     * The User Id endpoint returns the Id of the User, which was currently created.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userRegisterGetTest() throws ApiException {
        FroodyUser response = api.userRegisterGet();

        // TODO: test validations
    }
    
}
