/*
 * Froody API
 * API for Froody - http://froodyapp.gsantner.net/
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.froodyapp.api.invoker.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
