/*
 * Froody API
 * API for Froody application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.froodyapp.api.model_;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;
import java.io.Serializable;

/**
 * Informations about a Geohash-Block
 */
@ApiModel(description = "Informations about a Geohash-Block")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-27T19:43:32.369+02:00")
public class BlockInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("geohash")
  private String geohash = "";

  @SerializedName("modificationDate")
  private DateTime modificationDate = null;

  @SerializedName("hasBlockBeenModified")
  private Boolean hasBlockBeenModified = false;

  public BlockInfo geohash(String geohash) {
    this.geohash = geohash;
    return this;
  }

   /**
   * BlockInfo ** GeoHash of location(lat,lng)
   * @return geohash
  **/
  @ApiModelProperty(value = "BlockInfo ** GeoHash of location(lat,lng)")
  public String getGeohash() {
    return geohash;
  }

  public void setGeohash(String geohash) {
    this.geohash = geohash;
  }

  public BlockInfo modificationDate(DateTime modificationDate) {
    this.modificationDate = modificationDate;
    return this;
  }

   /**
   * BlockInfo ** Timestamp of last modification of entries in this block
   * @return modificationDate
  **/
  @ApiModelProperty(value = "BlockInfo ** Timestamp of last modification of entries in this block")
  public DateTime getModificationDate() {
    return modificationDate;
  }

  public void setModificationDate(DateTime modificationDate) {
    this.modificationDate = modificationDate;
  }

  public BlockInfo hasBlockBeenModified(Boolean hasBlockBeenModified) {
    this.hasBlockBeenModified = hasBlockBeenModified;
    return this;
  }

   /**
   * BlockInfo ** True if the block has changed since requested min modification time
   * @return hasBlockBeenModified
  **/
  @ApiModelProperty(value = "BlockInfo ** True if the block has changed since requested min modification time")
  public Boolean getHasBlockBeenModified() {
    return hasBlockBeenModified;
  }

  public void setHasBlockBeenModified(Boolean hasBlockBeenModified) {
    this.hasBlockBeenModified = hasBlockBeenModified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockInfo blockInfo = (BlockInfo) o;
    return Objects.equals(this.geohash, blockInfo.geohash) &&
        Objects.equals(this.modificationDate, blockInfo.modificationDate) &&
        Objects.equals(this.hasBlockBeenModified, blockInfo.hasBlockBeenModified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geohash, modificationDate, hasBlockBeenModified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockInfo {\n");
    
    sb.append("    geohash: ").append(toIndentedString(geohash)).append("\n");
    sb.append("    modificationDate: ").append(toIndentedString(modificationDate)).append("\n");
    sb.append("    hasBlockBeenModified: ").append(toIndentedString(hasBlockBeenModified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

